### ISSUE TITLE
Bug: remappings are not supported for `node_modules` dependencies

### ISSUE THREAD

**Issue by PaulRBerg** [NomicFoundation/hardhat#4194]
### Describe the feature

Scenario:

- Hardhat + Foundry project
- Install the npm package of a Foundry project, e.g. [`@sablier/v2-core`](https://www.npmjs.com/package/@sablier/v2-core)
- Add the proper remappings in `remappings.txt`, i.e. `@sablier/v2-core/=node_modules/@sablier/v2-core/src/`
- Import something from `@sablier/v2/core`, e.g. `import { LockupLinear } from "@sablier/v2-core/types/DataTypes.sol";`
- Hope that the import works

But the import does not work:

```text
Failed to resolve file: "/Users/prb/Workspace/templates/hardhat-template/node_modules/@sablier/v2-core/types/DataTypes.sol": No such file or directory (os error 2).
 Check configured remappings..
    --> "/Users/prb/Workspace/templates/hardhat-template/contracts/Greeter.sol"
        "@sablier/v2-core/types/DataTypes.sol"
```

It seems to me that what happens is that Hardhat disregards the remappings in `remappings.txt` when it finds a matching path in `node_modules`.

The feature request is to make remappings work with `node_modules`.

FWIW, this is a blocker for our integration partners that are on Hardhat. They have to copy-paste the Sablier code for now.

### Search terms

foundry,hardhat-foundry

### Environment

- node@18.16.0
- hardhat@2.17.0

**Comment by alcuadrado** [comment]
@fvictorio I think we should consider this to be a bug, right? If it's present in the local `remappings.txt` shouldn't that take priority? As there's an explicit intention set by the user to use the remmapped path.

**Comment by alcuadrado** [comment]
This is the root of the issue: https://github.com/NomicFoundation/hardhat/blob/main/packages/hardhat-foundry/src/foundry.ts#L49

We should check if it's an explicit remapping in `remappings.txt` and not ignore it.

**Comment by alcuadrado** [comment]
We continued exploring this with @fvictorio, and we'll fix it in the next sprint (starting tomorrow).

The fix should:
1. Check in the line posted above if the remapping is in `remappings.txt`, if it is, do not ignore it. — This would not work with `foundry.toml`, so there's probably better approaches to consider.
2. In [hardhat core's resolver](https://github.com/NomicFoundation/hardhat/blob/main/packages/hardhat-core/src/internal/solidity/resolver.ts#L112): don't treat replaced `importName`s as importNames, but as file paths AND source names instead.

**Comment by PaulRBerg** [comment]
This bug continues to be a blocker for our users:

https://github.com/NomicFoundation/hardhat/issues/4194

**Comment by fvictorio** [comment]
I'll be working on this today, so we should be able to release a fix early next week.

**Comment by alcuadrado** [comment]
@PaulRBerg I think your example is also affected by this forge behavior: https://github.com/alcuadrado/foundry-custom-remappings-priority/

**Comment by alcuadrado** [comment]
https://github.com/foundry-rs/foundry/issues/5540

**Comment by Evalir** [comment]
hey hey @alcuadrado — we recently landed the fix for 5540 on master: https://github.com/foundry-rs/foundry/pull/5541

let us know if there's anything else we can do to help with this! thank you for the thorough report/repro 🙏

**Comment by alcuadrado** [comment]
Thanks for fixing it so quickly, @Evalir! We'll release our side of this fix pretty soon.

**Comment by PaulRBerg** [comment]
Thank you both! This is helpful.

**Comment by fvictorio** [comment]
@PaulRBerg we just released this fix: [@nomicfoundation/hardhat-foundry@1.0.3](https://github.com/NomicFoundation/hardhat/releases/tag/%40nomicfoundation%2Fhardhat-foundry%401.0.3)

Please let me know if this doesn't fix the problem for you!

**Comment by PaulRBerg** [comment]
Thanks again, guys! I re-ran the steps mentioned in the OP, and the original bug has been fixed with v1.0.3, but it looks like there is another one now 😬

I'm getting a bunch of errors like this:

```text
ParserError: Source "@prb/math/src/src/ud2x18/Casting.sol" not found: File not found. Searched the following locations: "".
  --> @prb/math/src/UD2x18.sol:22:1:
```

It looks like the _relative_ imports within `@prb/math` itself are not working now! An extra `src` gets added in the resolved paths.

I've put together a repro on the [`foundry-sablier-deps`](https://github.com/PaulRBerg/hardhat-template/tree/foundry-sablier-deps) branch in my Hardhat template.

**Comment by fvictorio** [comment]
But does `forge build` work for you? It doesn't for me in that branch.

**Comment by PaulRBerg** [comment]
@fvictorio yep, `forge build` works. Have you run `foundryup` recently and [re-initialized the submodules](https://twitter.com/PaulRBerg/status/1629425771457531905)?

**Comment by fvictorio** [comment]
I ran foundryup but didn't re-initialize the submodules, let me try that.

**Comment by fvictorio** [comment]
It still doesn't work for me. This is what I'm doing:

```
git clone git@github.com:PaulRBerg/hardhat-template.git
cd hardhat-template
git checkout foundry-sablier-deps
pnpm i
forge install
forge build
```

and I get an error that is actually very similar to the one you are getting.

Running `git submodule deinit --force . && git submodule update --init --recursive` doesn't fix it.

**Comment by fvictorio** [comment]
Ok, running `pnpm i @prb/math @openzeppelin/contracts` makes `forge build` work, and then I get the error you mentioned. I'll look into it.

**Comment by fvictorio** [comment]
I'm super confused about this, to be honest. I think that `forge` is creating a wrong input for solc (or at least that's what it seems to me by looking at the build-info after running `forge build --build-info`), in the sense that the solc input is not self-contained. But it works because solc seems to be reading from the file system anyway even when used in standard json mode :confused: :confused:

I asked the solc team about this. If they confirm that this is a bug, then forge is working in this case because the solc bug cancels its own bug. If they say that this is intentional (which would be super weird, ngl), the I still think forge is doing something wrong because the generated input is not correct. This can affect contract verification, for example, unless I'm seriously missing something here.

That doesn't explain the problem in our side though! But I found that weird thing while looking into this, so I'm mentioning it here for completeness.

Btw, I'm re-opening this because it's clearly not fixed.

**Comment by PaulRBerg** [comment]
Thanks for the quick turnaround, @fvictorio. Sorry to hear about the potential bugs in both Forge and Solc 😞

Tagging @Evalir and @mattsse who have recently worked on remappings (ref https://github.com/foundry-rs/foundry/pull/5532)

> he solc bug cancels its own bug

lmao

**Comment by fvictorio** [comment]
Hey @Evalir, sorry for the confusion.

Yes, I think there is at least one scenario where forge creates a solc input that (unintentionally, I guess) depends on the default import callback used by solc. I shared some details and reproduction steps with @mds1.

At the very least I recommend doing something like what I mention in https://github.com/NomicFoundation/hardhat/issues/4290, since that will prevent non-self-contained inputs from working.

**Comment by mds1** [comment]
Posting aforementioned repro from @fvictorio below:

```
mkdir repro && cd repro
forge init

# remove tests and scripts to make the solc input more clear
rm -r test script

# install @prb/math with pnpm
pnpm init && pnpm install @prb/math

# modify the source file to import something from @prb/math
echo 'import "@prb/math/SD1x18.sol";' >> src/Counter.sol

# add remapping
echo "@prb/math/=node_modules/@prb/math/src/" > remappings.txt

# build and generate the build info file
forge build --build-info

# get the solc input and _put it in another directory_
jq .input out/build-info/*.json > ~/Desktop/input.json

# compile that solc input in that directory
cd ~/Desktop
solc --standard-json input.json
```

> Using pnpm is important, this doesn't happen with npm
> Also, I specifically imported SD1x18.sol and not, say, Common.sol because the former has relative imports while the latter doesn't. I'm mentioning this because I think it's an important hint to what's going on. If you look at the sources in the input.json file you'll see that the imports get broken when you get to SD1x18.sol, because the source name units of the files it depends on are something like node_modules/.pnpm/... instead of node_modules/@prb/math/....
> My first guess is that it's something related to symlinks

**Comment by fvictorio** [comment]
@PaulRBerg we just published [Hardhat v2.17.2](https://github.com/NomicFoundation/hardhat/releases/tag/hardhat%402.17.2) and [hardhat-foundry v1.1.1](https://github.com/NomicFoundation/hardhat/releases/tag/%40nomicfoundation%2Fhardhat-foundry%401.1.1) which should fix this problem (now for real, I hope!). Could you please give it a try?

**Comment by PaulRBerg** [comment]
Thanks @fvictorio. Can confirm that upgrading to the latest versions of the dependencies mentioned makes compiling with Hardhat work now 🙏

https://github.com/PaulRBerg/hardhat-template/commit/f506b3ec5d763d1c5a0b42c67479a61459c96936

**Comment by fvictorio** [comment]
Super glad to hear that. I'm going to tentatively close this then, but please let me know if you find some other problem.
