### ISSUE TITLE
Forking a network locally doesn't work anymore

### ISSUE THREAD

**Issue by kuco23** [NomicFoundation/hardhat#4974]
### Version of Hardhat

2.21.0

### What happened?

After updating hardhat from `2.20.1` to `2.21.0` forking a test node fails with `Error HH604: Error running JSON-RPC server: The Http server returned error status code: HTTP status client error (415 Unsupported Media Type) for url (https://flare-api.flare.network/ext/C/rpc)`.

### Minimal reproduction steps

Run `yarn hardhat node --fork https://coston-api.flare.network/ext/bc/C/rpc --fork-block-number 12508443`.

**Comment by fvictorio** [comment]
Hey @kuco23, kick question, is that network Avalanche's C-chain?

**Comment by kuco23** [comment]
yes, it is

**Comment by FournyP** [comment]
Hi, I faced the same issue using polygon mainnet :
With this configuration :
```
hardhat: {
  chainId: 137,
  forking: {
    url: "https://polygon.llamarpc.com",
    blockNumber: 54461490,
  },
},
```
```
Error: The Http server returned error status code: HTTP status client error (400 Bad Request) for url (https://polygon.llamarpc.com/)
```

And with a `infura.io` node, I got the following error :
```
Error: The Http server returned error status code: HTTP status client error (429 Too Many Requests) for url (https://polygon-mainnet.infura.io/v3/xxx)
```

**Comment by Doc-Pixel** [comment]
Getting the same issue with shibarium.

Rolled back to 2.20.0 and it works again

**Comment by fullkomnun** [comment]
I have an internal Ethereum network that I fork by targeting a Geth node running remotely (used to work with V2.20.0).
I get the same issue for it with V2.21.0 (forking public networks with Alchemy endpoints works though).

Here are the logs:

```
  hardhat:core:hre Running task node +5ms
  hardhat:core:hre Running node's super +0ms
  hardhat:core:hre Running task node:get-provider +0ms
  hardhat:core:hre Running node:get-provider's super +0ms
  hardhat:core:hre Creating provider for network hardhat +0ms
Error HH604: Error running JSON-RPC server: The Http server returned error status code: HTTP status client error (415 Unsupported Media Type) for url (http://geth-testnet:8545/)

HardhatError: HH604: Error running JSON-RPC server: The Http server returned error status code: HTTP status client error (415 Unsupported Media Type) for url (http://geth-testnet:8545/)
    at SimpleTaskDefinition.action (<REDACTED>/solidity/node_modules/hardhat/src/builtin-tasks/node.ts:372:17)
    at async Environment._runTaskDefinition (<REDACTED>/solidity/node_modules/hardhat/src/internal/core/runtime-environment.ts:359:14)
    at async OverriddenTaskDefinition._action (<REDACTED>/solidity/node_modules/hardhat-deploy/src/index.ts:769:5)
    at async Environment._runTaskDefinition (<REDACTED>/solidity/node_modules/hardhat/src/internal/core/runtime-environment.ts:359:14)
    at async Environment.run (<REDACTED>/solidity/node_modules/hardhat/src/internal/core/runtime-environment.ts:192:14)
    at async main (<REDACTED>/solidity/node_modules/hardhat/src/internal/cli/cli.ts:323:7)

    Caused by: Error: The Http server returned error status code: HTTP status client error (415 Unsupported Media Type) for url (http://geth-testnet:8545/)
Child process exited with code 1
```

I have an Ethereum RPC reverse proxy I use for debugging and it seems that "Content-Type" http header for requests is not defined. Setting it to "application/json" in the reverse proxy makes everything work.

**Comment by Wodann** [comment]
Thank you all for the detailed bug reports! 😃

A fix has been released in https://github.com/NomicFoundation/hardhat/releases/tag/hardhat%402.22.1

Please let us know if you have any further issues.

**Comment by KiranKBR** [comment]
I am getting same issue for infura Error: The Http server returned error status code: HTTP status client error (429 Too Many Requests) for url (https://polygon-mainnet.infura.io/v3/xxx)

**Comment by KiranKBR** [comment]
I think the issue with infura

**Comment by fassko** [comment]
Seems that this issue is still persistent in `2.22.2` version.

With this configuration

```
networks: {
    hardhat: {
        forking: {
            url: 'https://flare-api.flare.network/ext/bc/C/rpc',
        },
    },
  },
```

I try to run tests with the default hardhat template project and got this for all the test cases:

```
1) Lock
       Deployment
         Should set the right unlockTime:
     ProviderError: Invalid parent hash: 0x04a102b8a3aeca91cd66086c2dab92626c181e49b56f17f3cbcbaba3e0442f2f. Expected: 0x7239c262dd57da60d339b9ebe0e948067d168b0ebc387dc52f5430f8ae9c803c.
```

**Comment by Wodann** [comment]
> I try to run tests with the default hardhat template project and got this for all the test cases:

This error seems specifically related to trying to mine a block for non-mainnet forks. Would you mind creating a dedicated issue for that?
